version: '3.8'

services:

  raw-contratacao-ingestion-consumer:
    build:
      context: .
      dockerfile: Dockerfile
      target: raw-contratacao-ingestion-consumer
    container_name: pncp-raw-contratacao-ingestion-consumer
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
  
  licitabot-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: licitabot-scheduler
    container_name: pncp-licitabot-scheduler
    env_file:
      - .env
    depends_on:
      raw-contratacao-ingestion-consumer:
        condition: service_healthy
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pncp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pncp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    profiles: ["dev"]

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: pncp-rabbitmq
    env_file:
      - .env
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: pncp-network