version: '3.8'

services:

  raw-contratacao-ingestion-consumer:
    env_file:
      - .env.dev
  
  licitabot-scheduler:
    env_file:
      - .env.dev

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env.dev
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
  
  setup-service:
    env_file:
      - .env.dev
  
  base-service:
    env_file:
      - .env.dev

  debug-service:
    env_file:
      - .env.dev

  rabbitmq:
    env_file:
      - .env.dev