"""create initial tables

Revision ID: db21080428bf
Revises: 
Create Date: 2025-09-09 10:48:09.138290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db21080428bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratacoes',
    sa.Column('numero_controle_pncp', sa.String(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('numero_controle_pncp')
    )
    op.create_table('item_contratacoes',
    sa.Column('numero_controle_pncp', sa.String(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['numero_controle_pncp'], ['contratacoes.numero_controle_pncp'], ),
    sa.PrimaryKeyConstraint('numero_controle_pncp', 'numero_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_contratacoes')
    op.drop_table('contratacoes')
    # ### end Alembic commands ###
