from typing import Generator, Optional, Protocol

from licitabot.domain.entities import RawContratacao
from licitabot.domain.value_objects import NumeroControlePNCP, YearMonthDay


class RawContratacaoRepositoryInterface(Protocol):
    async def get(
        self, numero_controle_pncp: NumeroControlePNCP
    ) -> Optional[RawContratacao]: ...
    async def save(self, entity: RawContratacao, force: bool = False) -> None: ...
    async def delete(self, numero_controle_pncp: NumeroControlePNCP) -> None: ...
    async def commit(self) -> None: ...
    async def flush(self) -> None: ...
    async def rollback(self) -> None: ...


class RawContratacaoGatewayInterface(Protocol):
    async def fetch_updated_contratacoes(
        self, dataInicial: YearMonthDay, dataFinal: YearMonthDay
    ) -> Generator[RawContratacao, None, None]: ...
    async def fetch_number_of_entries(
        self, dataInicial: YearMonthDay, dataFinal: YearMonthDay
    ) -> int: ...
